version: "3.2"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.48.0.0/24
services:
  vmq-main:
    container_name: vmq-main
    image: vernemq/vernemq
    environment:
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
    ports:
      - "1883:1883"
      - "8888:8888"
      - "8080:8080"
    networks:
      default:
        ipv4_address: 172.48.0.2
  vmq:
    image: vernemq/vernemq
    depends_on:
      - vmq-main
    environment:
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
      - "DOCKER_VERNEMQ_DISCOVERY_NODE=172.48.0.2"